###
POST http://localhost:4004/odata/v4/catalog/updateSubaccountDestination
Content-Type: application/json

{
     "globalAccount": "4090cdaetrial",
     "subAccount": "trial",
     "destination": "TRIAL_NEW_ONE",
     "isActive": "X"
}